apiVersion: v1
kind: Service
metadata:
  name: sshd-nodeport
spec:
  type: NodePort
  selector:
    app: sshd
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 2222
      nodePort: 32222
